let vimplug_path = '~/.vim/autoload'
if has('win32')
  let vimplug_path = '~/vimfiles/autoload'
  set shell=powershell
  set shellcmdflag=-command
endif

let vim_plug = vimplug_path . '/plug.vim'


" auto-install vim-plug
if !filereadable(expand(vim_plug))
  let plugin_file = 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  execute "silent !mkdir -p " . vimplug_path
  if has('win32')
    execute "silent !(New-Object System.Net.WebClient).DownloadFile('" . plugin_file . "', '" . expand(vim_plug) . "')"
  else
    execute "silent !curl -fLo " . vim_plug . " " . plugin_file
  endif
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()
Plug 'tpope/vim-sensible'

Plug 'agude/vim-eldar'

Plug 'itchyny/lightline.vim'

Plug 'morhetz/gruvbox'

"Plug 'yko/mojo.vim', { 'do': 'make install' }

Plug 'kchmck/vim-coffee-script'

Plug 'scrooloose/nerdtree'

"Plug 'HerringtonDarkholme/yats.vim'

Plug 'leafgarland/typescript-vim'

Plug 'vim-syntastic/syntastic'

Plug 'Xuyuanp/nerdtree-git-plugin'

Plug 'lervag/vimtex'
call plug#end()

if has('syntax')
  syntax enable
  set bg=dark
  silent! colorscheme gruvbox
  hi Normal ctermbg=None
  hi NonText ctermbg=None
endif

set autoindent
set smartindent
set shiftwidth=2
set tabstop=2
set expandtab
set showmatch

let swapfile_dir = '.vim/swp//'
if has('win32')
  let swapfile_dir = 'vimfiles/swp//'
endif

if !isdirectory(expand('~/' . swapfile_dir))
  execute "silent !mkdir -p ~/" . swapfile_dir
endif

exec 'set directory=$HOME/' . swapfile_dir


"Syntastic settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_typescript_checkers = ['tslint']
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

let g:syntastic_tex_checkers = []

let g:vimtex_syntax_minted = [
  \ {
  \  'lang': 'perl',
  \  'environments': [ 'perlcode' ]
  \ }
  \]

" restore cursor on re-entry into a file
function! ResCur()
  if line("'\"") <= line("$")
    normal! g`"
    return 1
  endif
endfunction

augroup resCur
  autocmd!
  autocmd BufWinEnter * call ResCur()
augroup END


set guifont=Hack:h9:cANSI:qDRAFT
